### ISSUE TITLE
MySQL database names with special characters don't work

### ISSUE THREAD

**Issue by phofm** [jeromeschneider/Flake#3]
See https://github.com/jeromeschneider/Baikal/issues/157 (I’m being lazy and just copying from there):
Githubby says: 

> Databases containing special characters like "-" cause the SHOW TABLES statement to fail, so the install process won't run through. Adding backticks around the database name fixes this.
> 
> In the file: /Core/Database/Mysql.php change the line

```
$sSql = "SHOW TABLES FROM `" . $this->sDbName ."`";
```

**Comment by netgusto** [comment]
Thanks ! Fixed by 0a96f7c (Baïkal)
